### ISSUE TITLE
Update for Ghost 3.x

### ISSUE THREAD

**Issue by bmann** [fission-suite/heroku-ipfs-ghost#1]
Newest version of default theme should be included and checked-in.

Have no idea if this will just work by updating package.json and/or what the DB migration is.

**Comment by MCTaylor17** [comment]
@bmann Unfortunately, for **existing** sites, it's slightly more complicated than updating the package.json.  Ghost facilitates the process through their [ghost-cli upgrade tool](https://ghost.org/update/?v=2.0) which involves making a backup and running a single command.

It's not entirely obvious what this tool does, but I can confirm [it definitely make alterations to the database](https://forum.ghost.org/t/ghost-update-failed-2-36-to-3-0-rollback-blocked/9788).
