### ISSUE TITLE
Check casper theme in directly

### ISSUE THREAD

**Issue by bmann** [fission-suite/heroku-ipfs-ghost#2]
For this to work on Heroku, casper (or whatever theme you're using) needs to get checked in directly to the themes folder.

https://github.com/fission-suite/heroku-ipfs-ghost/tree/master/content/themes

Delete the casper symlink, and check in the theme directly into this folder.

**Comment by MCTaylor17** [comment]
I didn't encounter any problems leaving the symlink as it was.  I'm not sure if it was a version 2.x problem, but for the time being, I can't replicate the problem.

I did encounter something very similar with the storage adapter though.  It seems to pass the `Build` stage but fails during `Deploy`.

The specific error looks like this:

```bash
app[web.1]: /app/content/adapters/storage/ghost-storage-adapter-ipfs:1
app[web.1]: ../../../node_modules/ghost-storage-adapter-ipfs/
app[web.1]: ^
app[web.1]:
app[web.1]: SyntaxError: Unexpected token '.'
app[web.1]: at Module._compile (internal/modules/cjs/loader.js:895:18)
# stack trace...
```

If this problem re-emerges, we can re-open the issue and hopefully address it with a similar approach.
