### ISSUE TITLE
Dropped support for installing Ghost via npm

### ISSUE THREAD

**Issue by MCTaylor17** [fission-suite/heroku-ipfs-ghost#3]
# Summary

While troubleshooting storage adapter issues, I encountered a comment from the Ghost staff indicating dropped support for installing Ghost via npm.  It's unknown how this might impact this project at this time.

## Problem

Unknown

### Impact

May have development/deployment implications

## Solution

Unknown

# Detail

**Screenshots**
![image](https://user-images.githubusercontent.com/7216377/69994620-18009d00-1503-11ea-830a-ad26d5b7dbb1.png)

**Additional context**
Via: https://forum.ghost.org/t/ghost-npm-module-contentpath-for-storage-adaptors/6288/9

**Comment by bmann** [comment]
I don’t think we need to do anything with this unless it stops working completely. 

Even then, a bash script on deploy may solve this by running Ghost locally.
