### ISSUE TITLE
Re-enable minor update (or update documentation)

### ISSUE THREAD

**Issue by MCTaylor17** [fission-suite/heroku-ipfs-ghost#9]
According to documentation:

>>>
### Upgrading Ghost
On each deployment, the Heroku Node/npm build process will **auto-upgrade Ghost to the newest 3.x version**. To prevent this behavior, use npm 5+ (or yarn) to create a lockfile.
>>>

During upgrades, package lock was added and package files were changed from `^`(minor) to `~`(patch) based on a related conversation.  These will need to be reverted to allow for the described functionality.

**Comment by bmann** [comment]
Yep will likely archive current version of the README and trim it down to be very specific. 

Pro: package.lock means we know that the current version works when last tested. 

Con: every time dependencies are updated, new package.lock needs to be manually checked in. 

There are a number of ways to solve this. Will either encourage people to fork, turn this repo into a template, maybe use the “pull” app to stay up to date with this master, etc.

**Comment by MCTaylor17** [comment]
I just added PR #10  to address the README issue #7.  Beyond the citation in the OP, I also noticed another reference under the **Ghost v3.x** heading:

> - Removed `package-lock.json` so that newest packages are used automatically

**Comment by MCTaylor17** [comment]
> There are a number of ways to solve this. Will either encourage people to fork, turn this repo into a template, maybe use the “pull” app to stay up to date with this master, etc.

I just noticed you can deploy from branches as well 🤔 

![image](https://user-images.githubusercontent.com/7216377/70600872-aaf5a300-1ba5-11ea-9a25-3981aaa1dda4.png)

**Comment by bmann** [comment]
I've updated docs for now.
